# -*- coding: utf-8 -*-
"""Untitled56.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEVGfT08bpVaDilvPvMVUydFpg_Fqens
"""

# Question one :
my_list = []
def adj(my_list):
  return list(map(int,my_list))

adj([ 1 , 2 , 3.3 ])

# Question two :
String = input(" Enter A String : ")
the_front_half = String[:len(String)//2]
the_back_half = String[len(String)//2:]

if len(String)%2 == 0 :
   print(" The length is even, the front and back halves are the same length. " )
else :
  print (" The length is odd, the extra char goes in the front half.")

print("the_front_half : " + the_front_half)
print("the_back_half :" + the_back_half)

the_front_front_half = the_front_half[:len(the_front_half)//2]
the_front_back_half = the_front_half[len(the_front_half)//2:]
the_back_front_half = the_back_half[:len(the_back_half)//2]
the_back_back_half = the_back_half[len(the_back_half)//2:]

print (the_front_front_half + the_back_front_half )
print(the_front_back_half + the_back_back_half )

# Question three :
def seq(*values):
    my_set = set (values)
    return len(my_set) == len(values)

print(seq(1,5,7,9))
print(seq(2,4,5,5,7,9))

# Question four :
def bubblesort(elements):
	swapped = False
	for n in range(len(elements)-1, 0, -1):
		for i in range(n):
			if elements[i] > elements[i + 1]:
				swapped = True
				elements[i], elements[i + 1] = elements[i + 1], elements[i]
		if not swapped:
			return
elements = [10, 50, 80, 5, 30, 40, 90, 20]
print("Unsorted list is,")
print(elements)
bubblesort(elements)
print("Sorted Array is, ")
print(elements)

# Question five :
import random
n = random.randint(1, 100)
print(n)
for _ in range(10):
    user_number = int(input("Enter your guess number: "))

    if user_number == n:
        print(f"Congratulations! You guessed the number {n}.")
        play_again = input("Do you want to play again? (yes/no): ").lower()
        if play_again != "yes":
            print("Thanks for playing!")
            break
    elif user_number > n:
        print("Your guess is high.")
    else:
        print("Your guess is low.")

    if user_number > 100:
        print("This is not allowed.")

# Question six :
def Difference(array):
    n = len(array)
    The_left_to_right_diagonal = 0
    The_right_to_left_diagonal = 0
    for i in range(n):
        The_left_to_right_diagonal += array[i][i]
        The_right_to_left_diagonal += array[i][n - i - 1]
    return abs(The_left_to_right_diagonal - The_right_to_left_diagonal)
n = int(input())
array = []
for _ in range(n):
    row = list(map(int, input().split()))
    array.append(row)
Absolute_difference = Difference(array)
print(Absolute_difference)