# -*- coding: utf-8 -*-
"""LAB 1 python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18HN_DyW0Jy4HuGOSDvf8OnyvDczgJnOD
"""

# Question 1 : Write a Python program which accepts the user's first and last name and print them in reverse order with a space between them.
First_name = input("Enter Your Fisrt Name ")
Last_name = input("Enter Your Last Name ")
name = First_name + " " + Last_name
N = name.split()[::-1]
print(N)
l = []
for i in N:
    l.append(i)
print(" ".join(l))

# Question 2 :  Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn. Sample value of n is 5 Expected Result : 615
n = input ("Sample Value of n ")
Expected_Result = int(n) + int (n*2) + int(n*3)
print (Expected_Result)

# Question 3 : Write a Python program to print the following here document. Sample string : a string that you "don't" have to escape This is a ....... multi-line heredoc string --------> example
String =  '''a string that you "don't" have to escape
This
is a ....... multi-line
heredoc string --------> example '''

print (String)

# Question 4 : Write a Python program to get the volume of a sphere with radius 6.
pi = 3.14
r = 6
volume_of_sphere = 4/3 * pi * r**3
print("volume of sphere = " + str(volume_of_sphere))

# Question 5 : Write a Python program that will accept the base and height of a triangle and compute the area.
h = int(input())
b = int(input())
area_of_triangle = int((h * b) / 2)
print(area_of_triangle)

# Question 6 : Write a Python program to construct the following pattern, using a nested for loop. Search about method= end=””
rows = 5

for i in range(rows + 1):
    for j in range(i):
        print("*", end=" ")
    print()

for i in range(rows - 1, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

# Question 7 : Write a Python program that accepts a word from the user and reverse it.
word = input("Enter a word : ")
Reversed_word = word[::-1]
print(Reversed_word)

# Question 8 :  Write a Python program that prints all the numbers from 0 to 6 except 3 and 6.
for i in range (7) :
  if i != 3 and i != 6:
   print(i)

# Question 9 : Write a Python program to get the Fibonacci series between 0 to 50
num = 9
n1, n2 = 1, 1
print("Fibonacci Series:", n1, n2, end=" ")
for i in range(2, num):
    n3 = n1 + n2
    n1 = n2
    n2 = n3
    print(n3, end=" ")

print()

# Question 10 : write a python program that accepts a string and calculate the number of digits and letters

alpha,string=0,"I Am a Data Engineer : 1234567"
for i in string:
	if (i.isalpha()):
		alpha+=1
print("Number of Digit = ", len(string)-alpha)
print("Number of Alphabets = ", alpha)